module.exports={
    UDATA:'userdata',
    PRODATA:'prodata',
    USERCART:'userCart',
    CATOGARY:'catgories',
    ORDER:'orderCollection',
    WISHLIST:'WishList',
    BANNERS:'banners',
    OFFERS:'offers',
    ADDRESS:'address',
    COUPON:'coupons'
}